#!/usr/bin/env bash
set -euo pipefail

# ─── Ninken Installer ───────────────────────────────────────────────
# One-command setup: detects Docker, generates .env, builds & starts.
# Usage: ./install.sh [--port 4000] [--anthropic-key sk-...] [--model claude-sonnet-4-20250514]

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { printf "${CYAN}[ninken]${NC} %s\n" "$*"; }
ok()    { printf "${GREEN}[ninken]${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}[ninken]${NC} %s\n" "$*"; }
fail()  { printf "${RED}[ninken]${NC} %s\n" "$*" >&2; exit 1; }

# ─── Defaults ───────────────────────────────────────────────────────
PORT=4000
ANTHROPIC_KEY=""
AI_MODEL="claude-sonnet-4-20250514"

# ─── Parse arguments ────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)          PORT="$2";          shift 2 ;;
    --anthropic-key) ANTHROPIC_KEY="$2"; shift 2 ;;
    --model)         AI_MODEL="$2";      shift 2 ;;
    -h|--help)
      echo "Usage: ./install.sh [--port 4000] [--anthropic-key sk-...] [--model claude-sonnet-4-20250514]"
      exit 0
      ;;
    *) fail "Unknown argument: $1" ;;
  esac
done

# ─── Detect Docker ──────────────────────────────────────────────────
info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  fail "Docker is not installed. Please install Docker first: https://docs.docker.com/get-docker/"
fi

if ! docker compose version &>/dev/null; then
  fail "Docker Compose v2 is required. Please update Docker or install the compose plugin."
fi

ok "Docker $(docker --version | awk '{print $3}') detected"
ok "Docker Compose $(docker compose version --short) detected"

# ─── Generate .env ──────────────────────────────────────────────────
if [[ -f .env ]]; then
  warn ".env already exists — skipping generation (delete it to regenerate)"
else
  info "Generating .env from template..."
  COOKIE_SECRET=$(openssl rand -hex 32)

  cat > .env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
NINKEN_PORT=${PORT}
NEXT_PUBLIC_BASE_URL=http://localhost:${PORT}
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
NINKEN_AI_MODEL=${AI_MODEL}
NINKEN_COOKIE_SECRET=${COOKIE_SECRET}
EOF

  ok ".env created with auto-generated NINKEN_COOKIE_SECRET"
fi

# ─── Build ──────────────────────────────────────────────────────────
info "Building Ninken container..."
docker compose build 2>&1 | tee install.log

# ─── Start ──────────────────────────────────────────────────────────
info "Starting Ninken..."
docker compose up -d 2>&1 | tee -a install.log

# ─── Health check polling ───────────────────────────────────────────
info "Waiting for Ninken to become healthy..."

MAX_WAIT=90
ELAPSED=0
INTERVAL=3

while [[ $ELAPSED -lt $MAX_WAIT ]]; do
  STATUS=$(docker inspect --format='{{.State.Health.Status}}' ninken 2>/dev/null || echo "unknown")
  case "$STATUS" in
    healthy)
      ok "Ninken is healthy!"
      break
      ;;
    unhealthy)
      fail "Container reported unhealthy. Check logs: docker compose logs ninken"
      ;;
    *)
      sleep "$INTERVAL"
      ELAPSED=$((ELAPSED + INTERVAL))
      ;;
  esac
done

if [[ $ELAPSED -ge $MAX_WAIT ]]; then
  warn "Timed out waiting for health check (${MAX_WAIT}s). The container may still be starting."
  warn "Check status: docker compose ps"
  warn "Check logs:   docker compose logs ninken"
fi

# ─── Done ───────────────────────────────────────────────────────────
echo ""
ok "════════════════════════════════════════════════════"
ok "  Ninken is running at http://localhost:${PORT}"
ok "════════════════════════════════════════════════════"
echo ""
info "Useful commands:"
info "  docker compose logs -f ninken   — stream logs"
info "  docker compose restart ninken   — restart"
info "  docker compose down             — stop"
echo ""
