/**
 * OPSEC data: Operation scenarios (offensive) and defensive controls.
 * Used by the unified OPSEC page.
 */

import type { StealthLevel } from "./stealth-scores"

// ---------------------------------------------------------------------------
// Offensive: Operation Scenarios
// ---------------------------------------------------------------------------

export type OperationScenario = {
  id: string
  provider: "google" | "microsoft" | "github" | "gitlab" | "slack"
  service: string
  operation: string
  api: string
  stealthLevel: StealthLevel
  detectionVectors: string[]
  opsecNotes: string[]
}

export const OPERATION_SCENARIOS: OperationScenario[] = [
  // -----------------------------------------------------------------------
  // Google Workspace
  // -----------------------------------------------------------------------
  {
    id: "g-gmail-read",
    provider: "google",
    service: "Gmail",
    operation: "Read email message (no mark read)",
    api: "Gmail API — messages.get",
    stealthLevel: 1,
    detectionVectors: ["Token audit log (if reviewed)"],
    opsecNotes: ["Format=metadata to avoid body access logging", "Rate-limit reads to match normal user cadence"],
  },
  {
    id: "g-gmail-search",
    provider: "google",
    service: "Gmail",
    operation: "Search inbox by keyword",
    api: "Gmail API — messages.list (q=)",
    stealthLevel: 2,
    detectionVectors: ["Token audit log", "Query string visible in log entry"],
    opsecNotes: ["Search queries are logged verbatim", "Use broad queries to avoid suspicious keywords"],
  },
  {
    id: "g-gmail-attachment",
    provider: "google",
    service: "Gmail",
    operation: "Download email attachment",
    api: "Gmail API — attachments.get",
    stealthLevel: 2,
    detectionVectors: ["Token audit log"],
    opsecNotes: ["Avoid downloading many attachments in rapid succession", "Spread across sessions"],
  },
  {
    id: "g-gmail-mass-attach",
    provider: "google",
    service: "Gmail",
    operation: "Mass attachment download (>50)",
    api: "Gmail API — attachments.get batch",
    stealthLevel: 5,
    detectionVectors: ["Volume anomaly alert", "DLP rule trigger", "SOC investigation"],
    opsecNotes: ["Extremely high risk of detection", "Triggers volume-based DLP rules", "Complete other objectives first"],
  },
  {
    id: "g-drive-list",
    provider: "google",
    service: "Drive",
    operation: "List Drive files",
    api: "Drive API — files.list",
    stealthLevel: 2,
    detectionVectors: ["Drive audit log"],
    opsecNotes: ["Paginate with small page sizes", "Avoid listing entire drive in single request"],
  },
  {
    id: "g-drive-download",
    provider: "google",
    service: "Drive",
    operation: "Download Drive file",
    api: "Drive API — files.get?alt=media",
    stealthLevel: 2,
    detectionVectors: ["Drive audit log", "Data access log"],
    opsecNotes: ["Individual file downloads blend with normal usage", "Avoid sensitive/flagged documents"],
  },
  {
    id: "g-drive-search",
    provider: "google",
    service: "Drive",
    operation: "Search Drive by keyword",
    api: "Drive API — files.list (q=)",
    stealthLevel: 2,
    detectionVectors: ["Drive audit log", "Query logged"],
    opsecNotes: ["Search queries visible in audit log", "Use generic terms"],
  },
  {
    id: "g-drive-bulk",
    provider: "google",
    service: "Drive",
    operation: "Bulk Drive download (>100 files)",
    api: "Drive API — batch",
    stealthLevel: 5,
    detectionVectors: ["Volume anomaly alert", "DLP rules trigger"],
    opsecNotes: ["Near-certain SOC response", "Use only when extraction is the primary objective"],
  },
  {
    id: "g-admin-users",
    provider: "google",
    service: "Admin",
    operation: "List users (Admin SDK)",
    api: "Directory API — users.list",
    stealthLevel: 3,
    detectionVectors: ["Admin audit log", "Flagged in security review"],
    opsecNotes: ["Admin API access is commonly monitored", "Paginate slowly", "Consider timing"],
  },
  {
    id: "g-admin-groups",
    provider: "google",
    service: "Admin",
    operation: "List groups",
    api: "Directory API — groups.list",
    stealthLevel: 3,
    detectionVectors: ["Admin audit log"],
    opsecNotes: ["Combine with user listing to look like admin activity", "Use during business hours"],
  },
  {
    id: "g-admin-roles",
    provider: "google",
    service: "Admin",
    operation: "List roles/permissions",
    api: "Admin SDK — roles.list",
    stealthLevel: 3,
    detectionVectors: ["Admin audit log"],
    opsecNotes: ["Permission enumeration is suspicious in review", "Get what you need and stop"],
  },
  {
    id: "g-admin-reports",
    provider: "google",
    service: "Admin",
    operation: "Admin Reports (login activity)",
    api: "Reports API — activities.list",
    stealthLevel: 4,
    detectionVectors: ["Auditing the auditors", "High visibility in security tools"],
    opsecNotes: ["Accessing security reporting APIs is a red flag", "Only if you need to understand monitoring posture"],
  },
  {
    id: "g-alert-center",
    provider: "google",
    service: "Admin",
    operation: "Alert Center access",
    api: "Alert Center API",
    stealthLevel: 4,
    detectionVectors: ["Security team notified", "Alert Center access logged"],
    opsecNotes: ["Defensive security tool access is extremely suspicious", "May reveal your presence if SOC correlates"],
  },
  {
    id: "g-calendar-list",
    provider: "google",
    service: "Calendar",
    operation: "Calendar events listing",
    api: "Calendar API — events.list",
    stealthLevel: 1,
    detectionVectors: ["Minimal logging"],
    opsecNotes: ["Very low risk", "Calendar reads are routine API operations"],
  },
  {
    id: "g-chat-read",
    provider: "google",
    service: "Chat",
    operation: "Chat spaces/messages read",
    api: "Chat API — spaces.messages.list",
    stealthLevel: 2,
    detectionVectors: ["Chat audit log"],
    opsecNotes: ["Message access logged in Workspace audit", "Stay in spaces the token owner belongs to"],
  },
  {
    id: "g-gcs-list",
    provider: "google",
    service: "Cloud Storage",
    operation: "GCS bucket listing",
    api: "Cloud Storage API — buckets.list",
    stealthLevel: 2,
    detectionVectors: ["Cloud Audit Log"],
    opsecNotes: ["Data Access Audit Logs may be enabled", "Check if org has comprehensive logging"],
  },
  {
    id: "g-gcs-download",
    provider: "google",
    service: "Cloud Storage",
    operation: "GCS object download",
    api: "Cloud Storage API — objects.get",
    stealthLevel: 2,
    detectionVectors: ["Data Access Audit Log"],
    opsecNotes: ["Object-level access logged when Data Access Logs enabled", "Check VPC-SC boundaries"],
  },
  {
    id: "g-contacts",
    provider: "google",
    service: "Contacts",
    operation: "Contact/People enumeration",
    api: "People API",
    stealthLevel: 1,
    detectionVectors: ["Minimal logging"],
    opsecNotes: ["Very low risk", "Useful for org reconnaissance"],
  },
  {
    id: "g-drive-activity",
    provider: "google",
    service: "Drive",
    operation: "Drive Activity access",
    api: "Drive Activity API",
    stealthLevel: 3,
    detectionVectors: ["Meta-audit access logged"],
    opsecNotes: ["Accessing activity logs may be flagged", "Reveals monitoring interest"],
  },
  {
    id: "g-groups-settings",
    provider: "google",
    service: "Admin",
    operation: "Groups Settings enumeration",
    api: "Groups Settings API",
    stealthLevel: 3,
    detectionVectors: ["Admin audit log"],
    opsecNotes: ["Settings enumeration indicates recon intent", "Combine with normal group listing"],
  },

  // -----------------------------------------------------------------------
  // Microsoft 365
  // -----------------------------------------------------------------------
  {
    id: "m-outlook-read",
    provider: "microsoft",
    service: "Outlook",
    operation: "Read Outlook message",
    api: "Graph — /messages/{id}",
    stealthLevel: 1,
    detectionVectors: ["Unified Audit Log (if enabled)"],
    opsecNotes: ["UAL is not enabled by default in all tenants", "Single message reads blend with normal traffic"],
  },
  {
    id: "m-outlook-search",
    provider: "microsoft",
    service: "Outlook",
    operation: "Search Outlook",
    api: "Graph — /messages?$search=",
    stealthLevel: 2,
    detectionVectors: ["UAL", "Query logged"],
    opsecNotes: ["Search terms are captured in UAL", "Avoid suspicious keywords"],
  },
  {
    id: "m-outlook-bulk",
    provider: "microsoft",
    service: "Outlook",
    operation: "Bulk mail download",
    api: "Graph — /messages batch",
    stealthLevel: 4,
    detectionVectors: ["Volume in UAL", "Possible DLP trigger"],
    opsecNotes: ["Large mailbox export is detectable", "Spread across time windows", "Use delta queries"],
  },
  {
    id: "m-onedrive-browse",
    provider: "microsoft",
    service: "OneDrive",
    operation: "Browse OneDrive files",
    api: "Graph — /drive/root/children",
    stealthLevel: 2,
    detectionVectors: ["UAL file access"],
    opsecNotes: ["File browsing is common but logged", "Pagination reduces signal"],
  },
  {
    id: "m-onedrive-download",
    provider: "microsoft",
    service: "OneDrive",
    operation: "Download OneDrive file",
    api: "Graph — /drive/items/{id}/content",
    stealthLevel: 2,
    detectionVectors: ["UAL data access"],
    opsecNotes: ["Individual downloads are low risk", "Avoid files marked as sensitive"],
  },
  {
    id: "m-teams-messages",
    provider: "microsoft",
    service: "Teams",
    operation: "Read Teams messages",
    api: "Graph — /teams/{id}/channels/{id}/messages",
    stealthLevel: 2,
    detectionVectors: ["UAL if advanced audit enabled"],
    opsecNotes: ["Teams message access requires advanced audit license to log", "Stay in joined teams"],
  },
  {
    id: "m-entra-users",
    provider: "microsoft",
    service: "Entra ID",
    operation: "List Entra users",
    api: "Graph — /users",
    stealthLevel: 3,
    detectionVectors: ["Directory read logged", "Conditional Access evaluation"],
    opsecNotes: ["Directory enumeration is common but reviewed", "CA policies may block based on client"],
  },
  {
    id: "m-entra-groups",
    provider: "microsoft",
    service: "Entra ID",
    operation: "List Entra groups",
    api: "Graph — /groups",
    stealthLevel: 3,
    detectionVectors: ["Directory read logged"],
    opsecNotes: ["Group enumeration reveals org structure", "Use $select to minimize data"],
  },
  {
    id: "m-entra-roles",
    provider: "microsoft",
    service: "Entra ID",
    operation: "List directory roles",
    api: "Graph — /directoryRoles",
    stealthLevel: 3,
    detectionVectors: ["Directory audit log"],
    opsecNotes: ["Role enumeration may trigger anomaly detection", "Useful for privilege escalation recon"],
  },
  {
    id: "m-ca-read",
    provider: "microsoft",
    service: "Entra ID",
    operation: "Conditional Access read",
    api: "Graph — /conditionalAccess/policies",
    stealthLevel: 3,
    detectionVectors: ["Security config access logged"],
    opsecNotes: ["Reading CA policies reveals you are mapping defenses", "Essential for understanding token controls"],
  },
  {
    id: "m-signin-logs",
    provider: "microsoft",
    service: "Entra ID",
    operation: "Sign-in logs access",
    api: "Graph — /auditLogs/signIns",
    stealthLevel: 4,
    detectionVectors: ["Auditing the auditors"],
    opsecNotes: ["Accessing sign-in logs is a strong signal of adversary activity", "High value but high risk"],
  },
  {
    id: "m-risk-detections",
    provider: "microsoft",
    service: "Entra ID",
    operation: "Risk detections",
    api: "Graph — /riskDetections",
    stealthLevel: 4,
    detectionVectors: ["Security data access logged"],
    opsecNotes: ["Indicates attacker assessing if they are detected", "Only access if critical to operation"],
  },
  {
    id: "m-auth-methods",
    provider: "microsoft",
    service: "Entra ID",
    operation: "Auth methods enumeration",
    api: "Graph — /users/{id}/authentication/methods",
    stealthLevel: 4,
    detectionVectors: ["Sensitive security data access"],
    opsecNotes: ["MFA enumeration is highly suspicious", "May indicate pre-persistence activity"],
  },
  {
    id: "m-foci-pivot",
    provider: "microsoft",
    service: "Entra ID",
    operation: "FOCI client ID pivot",
    api: "Token refresh with different client_id",
    stealthLevel: 3,
    detectionVectors: ["Unusual client ID in sign-in log"],
    opsecNotes: ["Client ID switch visible in sign-in logs", "Use common FOCI client IDs to blend in"],
  },
  {
    id: "m-cross-tenant",
    provider: "microsoft",
    service: "Entra ID",
    operation: "Cross-tenant access read",
    api: "Graph — /crossTenantAccessPolicy",
    stealthLevel: 3,
    detectionVectors: ["Policy read logged"],
    opsecNotes: ["Reveals interest in tenant boundaries", "Useful for lateral movement planning"],
  },

  // -----------------------------------------------------------------------
  // GitHub
  // -----------------------------------------------------------------------
  {
    id: "gh-repos-list",
    provider: "github",
    service: "Repos",
    operation: "List repos",
    api: "REST — /user/repos",
    stealthLevel: 1,
    detectionVectors: ["None (standard API)"],
    opsecNotes: ["Standard API usage", "No audit logging for personal repos"],
  },
  {
    id: "gh-code-search",
    provider: "github",
    service: "Search",
    operation: "Code search",
    api: "REST — /search/code",
    stealthLevel: 1,
    detectionVectors: ["Rate limited, no alert"],
    opsecNotes: ["Search is rate-limited but not alerted", "Useful for finding secrets, keys, config"],
  },
  {
    id: "gh-org-members",
    provider: "github",
    service: "Organization",
    operation: "List org members",
    api: "REST — /orgs/{org}/members",
    stealthLevel: 2,
    detectionVectors: ["Org audit log"],
    opsecNotes: ["Org audit log captures member enumeration", "Available to org admins"],
  },
  {
    id: "gh-repo-secrets",
    provider: "github",
    service: "Actions",
    operation: "List repo secrets (names)",
    api: "REST — /repos/{o}/{r}/actions/secrets",
    stealthLevel: 3,
    detectionVectors: ["Security tab access logged"],
    opsecNotes: ["Secret names visible but not values", "Access is logged in org audit"],
  },
  {
    id: "gh-webhooks",
    provider: "github",
    service: "Repos",
    operation: "List webhooks",
    api: "REST — /repos/{o}/{r}/hooks",
    stealthLevel: 3,
    detectionVectors: ["Admin access logged"],
    opsecNotes: ["Webhook URLs may contain tokens/secrets", "Requires admin access to repo"],
  },
  {
    id: "gh-deploy-keys",
    provider: "github",
    service: "Repos",
    operation: "List deploy keys",
    api: "REST — /repos/{o}/{r}/keys",
    stealthLevel: 2,
    detectionVectors: ["Standard access"],
    opsecNotes: ["Deploy keys provide repo-level access", "Useful for persistence reconnaissance"],
  },
  {
    id: "gh-workflows",
    provider: "github",
    service: "Actions",
    operation: "Actions workflows",
    api: "REST — /repos/{o}/{r}/actions/workflows",
    stealthLevel: 1,
    detectionVectors: ["Standard access"],
    opsecNotes: ["Workflow enumeration is normal developer activity", "Check for self-hosted runners"],
  },
  {
    id: "gh-gists",
    provider: "github",
    service: "Gists",
    operation: "Gist listing",
    api: "REST — /gists",
    stealthLevel: 1,
    detectionVectors: ["No logging"],
    opsecNotes: ["Gists may contain secrets, config, or internal data", "Check secret gists"],
  },

  // -----------------------------------------------------------------------
  // GitLab
  // -----------------------------------------------------------------------
  {
    id: "gl-projects-list",
    provider: "gitlab",
    service: "Projects",
    operation: "List projects",
    api: "REST — /projects",
    stealthLevel: 1,
    detectionVectors: ["Standard API"],
    opsecNotes: ["Normal developer activity", "No special logging"],
  },
  {
    id: "gl-repo-tree",
    provider: "gitlab",
    service: "Repos",
    operation: "Browse repo tree",
    api: "REST — /projects/{id}/repository/tree",
    stealthLevel: 1,
    detectionVectors: ["Standard API"],
    opsecNotes: ["Tree browsing is routine", "Useful for finding config files"],
  },
  {
    id: "gl-file-read",
    provider: "gitlab",
    service: "Repos",
    operation: "Read file content",
    api: "REST — /projects/{id}/repository/files",
    stealthLevel: 2,
    detectionVectors: ["Possible audit log"],
    opsecNotes: ["File access may appear in project audit events", "Target specific files"],
  },
  {
    id: "gl-ci-vars",
    provider: "gitlab",
    service: "CI/CD",
    operation: "CI/CD variables",
    api: "REST — /projects/{id}/variables",
    stealthLevel: 3,
    detectionVectors: ["Secret access logged", "Audit event"],
    opsecNotes: ["Variable access is audited on Premium+", "High-value target for credentials"],
  },
  {
    id: "gl-runners",
    provider: "gitlab",
    service: "CI/CD",
    operation: "Runner enumeration",
    api: "REST — /runners",
    stealthLevel: 2,
    detectionVectors: ["Standard API"],
    opsecNotes: ["Runner info reveals infrastructure", "Check for shared vs specific runners"],
  },
  {
    id: "gl-deploy-tokens",
    provider: "gitlab",
    service: "Deploy",
    operation: "List deploy tokens",
    api: "REST — /deploy_tokens",
    stealthLevel: 2,
    detectionVectors: ["Token management access"],
    opsecNotes: ["Deploy tokens provide persistent access", "Useful for persistence planning"],
  },
  {
    id: "gl-groups",
    provider: "gitlab",
    service: "Groups",
    operation: "Group listing",
    api: "REST — /groups",
    stealthLevel: 1,
    detectionVectors: ["Standard API"],
    opsecNotes: ["Normal developer operation", "Reveals org structure"],
  },
  {
    id: "gl-snippets",
    provider: "gitlab",
    service: "Snippets",
    operation: "Snippet listing",
    api: "REST — /snippets",
    stealthLevel: 1,
    detectionVectors: ["Standard API"],
    opsecNotes: ["Snippets may contain secrets or sensitive config", "Check internal snippets"],
  },

  // -----------------------------------------------------------------------
  // Slack
  // -----------------------------------------------------------------------
  {
    id: "sl-channels-list",
    provider: "slack",
    service: "Channels",
    operation: "List channels",
    api: "conversations.list",
    stealthLevel: 1,
    detectionVectors: ["Standard (Enterprise: audit log)"],
    opsecNotes: ["Free/Pro: no logging", "Enterprise Grid: Audit Log API captures this"],
  },
  {
    id: "sl-messages-read",
    provider: "slack",
    service: "Messages",
    operation: "Read messages",
    api: "conversations.history",
    stealthLevel: 2,
    detectionVectors: ["Enterprise: DLP + audit log"],
    opsecNotes: ["Message access logged on Enterprise Grid", "DLP rules may flag content"],
  },
  {
    id: "sl-files-list",
    provider: "slack",
    service: "Files",
    operation: "List files",
    api: "files.list",
    stealthLevel: 2,
    detectionVectors: ["Enterprise: audit log"],
    opsecNotes: ["File enumeration logged on Enterprise", "Check file types for sensitive data"],
  },
  {
    id: "sl-users-list",
    provider: "slack",
    service: "Users",
    operation: "List users",
    api: "users.list",
    stealthLevel: 1,
    detectionVectors: ["Standard API"],
    opsecNotes: ["Normal workspace activity", "Useful for org chart reconnaissance"],
  },
  {
    id: "sl-file-download",
    provider: "slack",
    service: "Files",
    operation: "Download file",
    api: "files.info + url",
    stealthLevel: 2,
    detectionVectors: ["Enterprise: audit log"],
    opsecNotes: ["File downloads logged on Enterprise", "Avoid bulk downloads"],
  },
]

// ---------------------------------------------------------------------------
// Defensive: Controls per provider
// ---------------------------------------------------------------------------

export type ControlStatus = "available" | "enabled-by-default" | "does-not-exist" | "preview"
export type ControlEffectiveness = "very-high" | "high" | "medium" | "low" | "detective-only"

export type DefensiveControl = {
  id: string
  provider: "google" | "microsoft" | "github" | "gitlab" | "slack"
  control: string
  description: string
  status: ControlStatus
  effectiveness: ControlEffectiveness
  notes: string
  category: "preventive" | "detective" | "responsive"
}

export const DEFENSIVE_CONTROLS: DefensiveControl[] = [
  // -----------------------------------------------------------------------
  // Google Workspace
  // -----------------------------------------------------------------------
  {
    id: "g-caa",
    provider: "google",
    control: "Context-Aware Access (CAA)",
    description: "Restrict access based on device posture, IP, location. Can block API access from unmanaged devices.",
    status: "available",
    effectiveness: "very-high",
    notes: "Requires BeyondCorp Enterprise or Workspace Enterprise. Blocks stolen tokens from non-compliant devices.",
    category: "preventive",
  },
  {
    id: "g-oauth-whitelist",
    provider: "google",
    control: "OAuth App Whitelisting",
    description: "Restrict which OAuth client IDs can request tokens. Blocks unauthorized third-party apps.",
    status: "available",
    effectiveness: "high",
    notes: "Admin Console > Security > API Controls. Blocks token theft via malicious OAuth apps.",
    category: "preventive",
  },
  {
    id: "g-vpc-sc",
    provider: "google",
    control: "VPC Service Controls for Workspace",
    description: "Network-level perimeter around Workspace data. Would block token use from outside perimeter.",
    status: "does-not-exist",
    effectiveness: "very-high",
    notes: "VPC-SC exists for GCP but does NOT cover Workspace APIs (Gmail, Drive, Calendar). Major gap.",
    category: "preventive",
  },
  {
    id: "g-workspace-dlp",
    provider: "google",
    control: "Workspace DLP Rules",
    description: "Data Loss Prevention rules for Gmail, Drive, Chat. Detect and block sensitive data exfiltration.",
    status: "available",
    effectiveness: "medium",
    notes: "Requires Workspace Enterprise. Detective control — alerts on sensitive content but doesn't block API access.",
    category: "detective",
  },
  {
    id: "g-alert-center-ctrl",
    provider: "google",
    control: "Alert Center Rules",
    description: "Custom and built-in alert rules for suspicious activity. SOC receives notifications.",
    status: "available",
    effectiveness: "medium",
    notes: "Requires SOC to actively monitor. Alerts on anomalous login, data export, admin actions.",
    category: "detective",
  },
  {
    id: "g-token-revocation",
    provider: "google",
    control: "Automatic Token Revocation",
    description: "Auto-revoke tokens when password changes or session is invalidated.",
    status: "enabled-by-default",
    effectiveness: "medium",
    notes: "Password change revokes refresh tokens. Session-length policies limit token lifetime.",
    category: "responsive",
  },
  {
    id: "g-audit-log",
    provider: "google",
    control: "Admin Audit Logs",
    description: "Comprehensive audit logging for admin and user activities.",
    status: "enabled-by-default",
    effectiveness: "detective-only",
    notes: "Logs exist but require active review. Token operations recorded. 6-month retention by default.",
    category: "detective",
  },
  {
    id: "g-session-control",
    provider: "google",
    control: "Session Length Controls",
    description: "Force re-authentication after configurable time period. Limits token lifetime.",
    status: "available",
    effectiveness: "medium",
    notes: "Admin Console > Security > Google Session Control. Can set 1h-24h limits.",
    category: "preventive",
  },
  {
    id: "g-token-binding",
    provider: "google",
    control: "Token Binding / Device Binding",
    description: "Bind tokens to specific device certificates or TPM. Prevents token export.",
    status: "does-not-exist",
    effectiveness: "very-high",
    notes: "Google does not offer token-to-device binding for Workspace tokens. Tokens can be freely exported.",
    category: "preventive",
  },
  {
    id: "g-cae",
    provider: "google",
    control: "Continuous Access Evaluation",
    description: "Real-time policy evaluation during token use (not just at auth time).",
    status: "does-not-exist",
    effectiveness: "very-high",
    notes: "Google lacks CAE equivalent. Tokens remain valid until expiry regardless of policy changes.",
    category: "preventive",
  },

  // -----------------------------------------------------------------------
  // Microsoft 365
  // -----------------------------------------------------------------------
  {
    id: "m-ca",
    provider: "microsoft",
    control: "Conditional Access (CA)",
    description: "Policy engine evaluating sign-in conditions: IP, device compliance, risk level, app.",
    status: "available",
    effectiveness: "very-high",
    notes: "Requires Entra ID P1/P2. Evaluated at token issuance. Does NOT revoke existing tokens.",
    category: "preventive",
  },
  {
    id: "m-cae",
    provider: "microsoft",
    control: "Continuous Access Evaluation (CAE)",
    description: "Real-time token revocation when critical events occur (password change, IP change, risk detection).",
    status: "available",
    effectiveness: "very-high",
    notes: "Extends token lifetime to 28h but adds real-time policy checks. Covers Graph API calls.",
    category: "preventive",
  },
  {
    id: "m-token-protection",
    provider: "microsoft",
    control: "Token Protection (Proof-of-Possession)",
    description: "Cryptographically bind tokens to the device that requested them. Stolen tokens become unusable.",
    status: "preview",
    effectiveness: "very-high",
    notes: "In preview. When GA, will make token theft attacks significantly harder. Currently limited scope.",
    category: "preventive",
  },
  {
    id: "m-ual",
    provider: "microsoft",
    control: "Unified Audit Log (UAL)",
    description: "Centralized audit log for all M365 services. Captures mail access, file downloads, admin actions.",
    status: "available",
    effectiveness: "detective-only",
    notes: "Must be explicitly enabled. 90-day retention (E5: 1 year). Essential for incident response.",
    category: "detective",
  },
  {
    id: "m-risky-signin",
    provider: "microsoft",
    control: "Risky Sign-In Detection",
    description: "ML-based detection of anomalous sign-ins: impossible travel, anonymous IP, token anomaly.",
    status: "available",
    effectiveness: "high",
    notes: "Requires Entra ID P2. Can auto-block or require MFA step-up. Feeds into CA policies.",
    category: "detective",
  },
  {
    id: "m-defender-cloud",
    provider: "microsoft",
    control: "Defender for Cloud Apps (MCAS)",
    description: "CASB that monitors M365 app usage, detects anomalous behavior, can block sessions.",
    status: "available",
    effectiveness: "high",
    notes: "Session policies can restrict downloads in real-time. Requires E5 or standalone license.",
    category: "detective",
  },
  {
    id: "m-foci-block",
    provider: "microsoft",
    control: "FOCI Family Restriction",
    description: "Ability to restrict which FOCI client IDs can exchange tokens within a family.",
    status: "does-not-exist",
    effectiveness: "high",
    notes: "No control to block FOCI token exchange. Any app in family can pivot to any other family member.",
    category: "preventive",
  },
  {
    id: "m-revocation",
    provider: "microsoft",
    control: "Token Revocation (Immediate)",
    description: "Ability to immediately revoke all tokens for a user.",
    status: "available",
    effectiveness: "high",
    notes: "Revoke-AzureADUserAllRefreshToken. Takes up to 1 hour without CAE. CAE makes it near-instant.",
    category: "responsive",
  },
  {
    id: "m-device-compliance",
    provider: "microsoft",
    control: "Device Compliance Requirements",
    description: "Require managed/compliant devices for token issuance via Conditional Access.",
    status: "available",
    effectiveness: "high",
    notes: "Blocks token use from attacker-controlled devices. Requires Intune enrollment.",
    category: "preventive",
  },
  {
    id: "m-app-consent",
    provider: "microsoft",
    control: "App Consent Policies",
    description: "Control which OAuth apps users can consent to. Admin consent workflow.",
    status: "available",
    effectiveness: "medium",
    notes: "Blocks rogue OAuth app consent. Does not affect FOCI or first-party apps.",
    category: "preventive",
  },

  // -----------------------------------------------------------------------
  // GitHub
  // -----------------------------------------------------------------------
  {
    id: "gh-ip-allowlist",
    provider: "github",
    control: "IP Allowlist (Enterprise)",
    description: "Restrict API access to specific IP ranges. Blocks stolen PATs from unauthorized networks.",
    status: "available",
    effectiveness: "high",
    notes: "Enterprise Cloud only. Applies to API and web access. Must maintain IP list.",
    category: "preventive",
  },
  {
    id: "gh-pat-expiry",
    provider: "github",
    control: "PAT Expiration Policy",
    description: "Org policy requiring fine-grained PATs with maximum lifetime.",
    status: "available",
    effectiveness: "medium",
    notes: "Limits blast radius of stolen tokens. Does not prevent use during validity period.",
    category: "preventive",
  },
  {
    id: "gh-audit-log",
    provider: "github",
    control: "Org Audit Log",
    description: "Audit log for organization events: member changes, repo access, settings changes.",
    status: "available",
    effectiveness: "detective-only",
    notes: "Enterprise: streaming to SIEM. Free/Team: web UI only, limited retention.",
    category: "detective",
  },
  {
    id: "gh-secret-scanning",
    provider: "github",
    control: "Secret Scanning",
    description: "Detect committed secrets and tokens in repositories. Auto-revoke partner tokens.",
    status: "available",
    effectiveness: "medium",
    notes: "Push protection blocks commits with secrets. Partner program auto-revokes leaked tokens.",
    category: "detective",
  },
  {
    id: "gh-fine-grained-pat",
    provider: "github",
    control: "Fine-Grained PAT Restrictions",
    description: "Require fine-grained PATs instead of classic tokens. Scope tokens to specific repos.",
    status: "available",
    effectiveness: "medium",
    notes: "Org setting to block classic PATs. Fine-grained PATs have repo-level and permission-level scoping.",
    category: "preventive",
  },
  {
    id: "gh-sso-enforcement",
    provider: "github",
    control: "SAML SSO Enforcement",
    description: "Require SAML SSO for org access. PATs must be SSO-authorized.",
    status: "available",
    effectiveness: "high",
    notes: "Enterprise Cloud. PATs must be explicitly authorized for SSO orgs. Revocable by IdP.",
    category: "preventive",
  },
  {
    id: "gh-token-binding",
    provider: "github",
    control: "Token-to-Device Binding",
    description: "Bind PATs or session tokens to specific device identifiers.",
    status: "does-not-exist",
    effectiveness: "very-high",
    notes: "GitHub has no device binding for tokens. Any PAT works from any device/IP (unless IP allowlist).",
    category: "preventive",
  },
  {
    id: "gh-api-rate-anomaly",
    provider: "github",
    control: "API Rate Anomaly Detection",
    description: "Detect unusual API usage patterns that indicate compromised tokens.",
    status: "does-not-exist",
    effectiveness: "high",
    notes: "GitHub has rate limits but no anomaly-based alerting. Attackers can enumerate freely within rate limits.",
    category: "detective",
  },

  // -----------------------------------------------------------------------
  // GitLab
  // -----------------------------------------------------------------------
  {
    id: "gl-ip-restrict",
    provider: "gitlab",
    control: "IP Restrictions (Group Level)",
    description: "Restrict group access to specific IP ranges. Blocks API access from unauthorized networks.",
    status: "available",
    effectiveness: "high",
    notes: "Premium+ feature. Applies to group-level resources. Does not cover personal projects.",
    category: "preventive",
  },
  {
    id: "gl-pat-expiry",
    provider: "gitlab",
    control: "PAT Expiration Policy",
    description: "Instance-wide maximum PAT lifetime. Force rotation of long-lived tokens.",
    status: "available",
    effectiveness: "medium",
    notes: "Self-managed and SaaS Ultimate. Default max lifetime configurable by admin.",
    category: "preventive",
  },
  {
    id: "gl-audit-events",
    provider: "gitlab",
    control: "Audit Events",
    description: "Audit trail for security-relevant events: logins, permission changes, token creation.",
    status: "available",
    effectiveness: "detective-only",
    notes: "Premium+. Streaming to SIEM on Ultimate. Limited events on free tier.",
    category: "detective",
  },
  {
    id: "gl-secret-detection",
    provider: "gitlab",
    control: "Secret Detection (SAST)",
    description: "Scan commits and pipelines for leaked secrets and credentials.",
    status: "available",
    effectiveness: "medium",
    notes: "Part of GitLab SAST. Can block MRs with secrets. Does not auto-revoke.",
    category: "detective",
  },
  {
    id: "gl-token-binding",
    provider: "gitlab",
    control: "Token-to-Device Binding",
    description: "Bind PATs to specific devices or network contexts.",
    status: "does-not-exist",
    effectiveness: "very-high",
    notes: "GitLab has no device binding. Stolen PATs work from any device/network.",
    category: "preventive",
  },
  {
    id: "gl-ci-var-masking",
    provider: "gitlab",
    control: "CI/CD Variable Masking",
    description: "Mask CI/CD variables in job logs. Prevent accidental exposure.",
    status: "available",
    effectiveness: "low",
    notes: "Only masks in log output. Does not prevent API enumeration of variable values.",
    category: "preventive",
  },
  {
    id: "gl-deploy-token-scope",
    provider: "gitlab",
    control: "Deploy Token Scoping",
    description: "Scope deploy tokens to specific projects and access levels.",
    status: "available",
    effectiveness: "medium",
    notes: "Limits blast radius. Deploy tokens cannot be scoped to specific branches or paths.",
    category: "preventive",
  },
  {
    id: "gl-api-anomaly",
    provider: "gitlab",
    control: "API Usage Anomaly Detection",
    description: "Detect unusual API usage patterns indicating compromised credentials.",
    status: "does-not-exist",
    effectiveness: "high",
    notes: "GitLab has no built-in API anomaly detection. Must rely on external SIEM/UBA.",
    category: "detective",
  },

  // -----------------------------------------------------------------------
  // Slack
  // -----------------------------------------------------------------------
  {
    id: "sl-audit-log",
    provider: "slack",
    control: "Audit Log API (Enterprise Grid)",
    description: "Comprehensive audit logging for all workspace activity. Enterprise Grid only.",
    status: "available",
    effectiveness: "detective-only",
    notes: "Only on Enterprise Grid. Free/Pro/Business+ have no audit API. Essential for detection.",
    category: "detective",
  },
  {
    id: "sl-session-mgmt",
    provider: "slack",
    control: "Session Management (Enterprise Grid)",
    description: "Admin control over active sessions. Force logout, set session duration.",
    status: "available",
    effectiveness: "medium",
    notes: "Enterprise Grid only. Can invalidate stolen browser sessions. Limited to web/desktop.",
    category: "responsive",
  },
  {
    id: "sl-dlp",
    provider: "slack",
    control: "DLP Integration (Enterprise Grid)",
    description: "Data Loss Prevention scanning for messages and files.",
    status: "available",
    effectiveness: "medium",
    notes: "Enterprise Grid with partner DLP (Nightfall, etc.). Detects sensitive data sharing.",
    category: "detective",
  },
  {
    id: "sl-domain-allowlist",
    provider: "slack",
    control: "Approved Workspaces (Domain Restriction)",
    description: "Restrict which Slack workspaces can be accessed from managed devices.",
    status: "available",
    effectiveness: "medium",
    notes: "Requires managed devices/proxy. Blocks exfiltration to attacker workspaces.",
    category: "preventive",
  },
  {
    id: "sl-token-rotation",
    provider: "slack",
    control: "Automatic Token Rotation",
    description: "Auto-rotate OAuth tokens with configurable lifetime.",
    status: "available",
    effectiveness: "medium",
    notes: "OAuth apps can opt into token rotation. Browser session tokens (xoxc) have separate lifecycle.",
    category: "preventive",
  },
  {
    id: "sl-session-binding",
    provider: "slack",
    control: "Session Token Device Binding",
    description: "Bind xoxc browser session tokens to specific device fingerprints.",
    status: "does-not-exist",
    effectiveness: "very-high",
    notes: "xoxc tokens are freely exportable. d cookie provides minimal binding. Major attack surface.",
    category: "preventive",
  },
  {
    id: "sl-api-anomaly",
    provider: "slack",
    control: "API Anomaly Detection",
    description: "Detect unusual API patterns: bulk message reads, mass file downloads.",
    status: "does-not-exist",
    effectiveness: "high",
    notes: "Slack has rate limits but no anomaly detection. Enterprise DLP is the closest control.",
    category: "detective",
  },
  {
    id: "sl-free-audit",
    provider: "slack",
    control: "Audit Logging (Free/Pro/Business+)",
    description: "Audit trail for non-Enterprise Slack tiers.",
    status: "does-not-exist",
    effectiveness: "detective-only",
    notes: "No audit logging on Free/Pro/Business+. Complete blind spot for SOC teams. Major gap.",
    category: "detective",
  },
]

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export const ALL_PROVIDERS = ["google", "microsoft", "github", "gitlab", "slack"] as const
export type ProviderFilter = (typeof ALL_PROVIDERS)[number] | "all"

export const PROVIDER_LABELS: Record<(typeof ALL_PROVIDERS)[number], string> = {
  google: "Google Workspace",
  microsoft: "Microsoft 365",
  github: "GitHub",
  gitlab: "GitLab",
  slack: "Slack",
}

export function getScenariosByProvider(provider: ProviderFilter): OperationScenario[] {
  if (provider === "all") return OPERATION_SCENARIOS
  return OPERATION_SCENARIOS.filter((s) => s.provider === provider)
}

export function getControlsByProvider(provider: ProviderFilter): DefensiveControl[] {
  if (provider === "all") return DEFENSIVE_CONTROLS
  return DEFENSIVE_CONTROLS.filter((c) => c.provider === provider)
}
